### ISSUE TITLE
[Maoni Sample App] Gg 6

### ISSUE THREAD

**Issue by maoni-reporter** [rm3l/maoni#31]
Gg 6

**Context**
- Device language : English
- Device : SM-J111M
- Screen size : 480 x 800
- Device Type : Phone
- Manufacturer : samsung
- Native platform : [armeabi-v7a, armeabi]
- Screen density : 240 dpi
- Version code : 311
- Application ID : org.rm3l.maoni.sample
- Android version : Android 5.1.1 (SDK 22)
- Version name : 3.1.1

**Comment by rm3l** [comment]
Test from maoni-github
