### ISSUE TITLE
[Maoni Sample App]  

### ISSUE THREAD

**Issue by maoni-reporter** [rm3l/maoni#35]
**Context**
- Device language : English
- Device : Pixel
- Screen size : 1080 x 1794
- Device Type : Phone
- Manufacturer : Google
- Native platform : [arm64-v8a, ]
- Screen density : 420 dpi
- Version code : 311
- Application ID : org.rm3l.maoni.sample
- Version name : 3.1.1
- Android version : Android 7.1.1 (SDK 25)

**Comment by rm3l** [comment]
Test from maoni-github
