### ISSUE TITLE
[Maoni Sample App]  

### ISSUE THREAD

**Issue by maoni-reporter** [rm3l/maoni#37]
**Context**
- Native platform : [arm64-v8a, ]
- Version code : 311
- Screen size : 1079 x 1730
- Application ID : org.rm3l.maoni.sample
- Device : Pixel
- Version name : 3.1.1
- Device language : English
- Manufacturer : Google
- Device Type : Phone
- Screen density : 420 dpi
- Android version : Android O (SDK 25)

**Comment by rm3l** [comment]
Test from maoni-github
