### ISSUE TITLE
Disable screenshot functionality?

### ISSUE THREAD

**Issue by Kev1000000** [rm3l/maoni#42]
Hello, I'd like to disable the screenshot functionality, but it doesn't seem like this is one of the customizable options.  Would you consider adding this as a parameter?

**Comment by rm3l** [comment]
Hi @Kev1000000 . Indeed, this is not customizable at this time, since it was not the initial goal of Maoni. But I understand this use case. I'll add an option to disable logs and screen captures (they will be enabled by default).
Looking into it.

**Comment by Kev1000000** [comment]
Thanks so much!

**Comment by rm3l** [comment]
Hi @Kev1000000 !
Just to let you know that this feature has been implemented in the latest version: 4.0.1
You should now have access to the appropriate options in the Maoni.Builder object.
Feel free to reopen this if there is any issues with this feature.
Thanks again for your feedback.

**Comment by Kev1000000** [comment]
Thank you!
